### ISSUE TITLE
Not Really sure how to run this

### ISSUE THREAD

**Issue by patpatshow** [dealloc/icarus_editor#11]
I looked for run files but never found any
please let me know if I need to use an app or something to use this

**Comment by dealloc** [comment]
hi @patpatshow you can find the builds for each OS (Windows 10 and Windows 11 are currently supported) under [Releases](https://github.com/dealloc/icarus_editor/releases)

You can see #10 as well for a similar question :)
feel free to close the issue if this solved your problem
