### ISSUE TITLE
Error when extracting files with Extract-Packs.ps1

### ISSUE THREAD

**Issue by Legomayer** [dealloc/icarus_editor#14]
Hi, I recently found your program and did my best to install it, Flutter and Git I believe are working properly. The error powershell gives me makes it appear like I am missing a file or set of files

I was able to update the game resources just fine, I just can't seem to get the script to fully run
I followed the update instructions as best as I could. Google, of course, is no help with something this specific
This is what my error looks like:
![Error](https://github.com/user-attachments/assets/b500aac2-2e15-4164-b201-caf582fe086c)
I have made sure to triple check my game install integrity, as well as check off each file included in the full zip

Please let me know if I need to install an extension for flutter or git, or if I am just over complicating this
Usually can figure this stuff out but I don't know if I'm gonna get this one lol

**Comment by Legomayer** [comment]
Small update, I found the file the script was looking for, guess a directory changed or something in the last few months with flutter or something else happened, either way, I am, as of this post, still working on a solution

for additional context should anyone else have my same issue:
my flutter is installed at:
c:\users\username\dev\flutter
and the package_config file is located at:
c:\users\username\dev\flutter\packages\flutter_tools\.dart_tool\package_config.json

**Comment by Legomayer** [comment]
pfff never mind me i was making it too complicated lol, cool process of updating the repository though

**Comment by dealloc** [comment]
hey @Legomayer as you probably found by now (but including for future reference if anyone else runs into this issue)
you can always simply download a prebuilt version from https://github.com/dealloc/icarus_editor/releases
