### ISSUE TITLE
Launcher is blank for Windows 64

### ISSUE THREAD

**Issue by laosurvey** [dealloc/icarus_editor#6]
Hello, when I downloaded the latest version for Windows x64 I got a blank screen. Something I'm doing wrong?

![image](https://github.com/dealloc/icarus_editor/assets/134117807/35affb27-b65e-4f8b-9f64-90911a889337)

**Comment by dealloc** [comment]
What version of Windows are you running (10/11/?)
Is Icarus installed, and if so does it have save files and where?

Do you have an antivirus running that might block things like this?

**Comment by laosurvey** [comment]
Windows 10. Icarus is installed via Steam in the default filepaths. Save game files are in C:\Users\USERNAME\AppData\Local\Icarus\Saved and game files in C:\Program Files (x86)\Steam\steamapps\common\Icarus. Only the default Windows protections were active.

Thanks for the quick response!

**Comment by dealloc** [comment]
hmm, I'm running Windows 11 myself, and I've never tested this on 10.
Might be some native libraries running into problems (the builds generated are also on W11 [link](https://github.com/dealloc/icarus_editor/blob/master/.github/workflows/release.yml#L9))

I'll see about making a separate build for Windows 10, and see if that works for you.
I'll keep this ticket open until such a build is available

**Comment by laosurvey** [comment]
Thank you man, really appreciate it.

**Comment by laosurvey** [comment]
Works perfectly now, great work!
