### ISSUE TITLE
Exotics doesn't work. 

### ISSUE THREAD

**Issue by Iamnuff** [dealloc/icarus_editor#8]
Using the windows 10 version, the 'currency' and 'refund tokens' fields both work fine but the 'Exotics' field doesn't do anything. 
Currently on zero, if I put 50 in there then press save changes, it asks for confirmation and then resets it back to zero.

I don't know if this is because I need to do something in-game to unlock exotics, or if the save-editor just isn't recognizing changes made to that field.

**Comment by dealloc** [comment]
Icarus only allows you to use Exotics once you've completed the mission required to get them ([Deep Vein: Extraction](https://icarus.fandom.com/wiki/Deep_Vein:_Extraction)).
Have you completed that mission?
